import { ProductFromServer } from '../../common/ts/interfaces/product.interface';

export const products: ProductFromServer[] = [
  {
    id: '74089-L0-00',
    name: 'NEW BIANCA',
    img: './assets/img/newBianka.jpeg',
    amount: 45,
    color: 'Black',
    price: 399,
    size: 38,
    collection: 2022,
    description: 'Lakierowane klasyczne czółenka z dużym metalowym monogramem',
    marka: 'Kazar',
    popular: false,
  },
  {
    id: '60722-01-13',
    name: 'VANILA',
    img: './assets/img/vanilla.jpeg',
    amount: 13,
    color: 'Gold',
    price: 449,
    size: 35,
    collection: 2022,
    description: 'Eleganckie złote sandały na niskim słupku',
    marka: 'Rylko',
    popular: false,
  },
  {
    id: '69843-01-20',
    name: 'FELIZIA',
    img: './assets/img/felizia.jpeg',
    amount: 22,
    color: 'Olive',
    price: 359,
    size: 37,
    collection: 2022,
    description: 'Ciemnobeżowe klapki damskie z kwadratowym noskiem',
    marka: 'Kazar',
    popular: true,
  },
  {
    id: '70104-01-B6',
    name: 'SOTERA',
    img: './assets/img/sotera.jpeg',
    amount: 2,
    color: 'Nude',
    price: 399,
    size: 38,
    collection: 2022,
    description: 'Stylowe skórzane japonki na platformie',
    marka: 'CCC',
    popular: false,
  },
  {
    id: '63468-L0-N4',
    name: 'NEW NATALIE',
    img: './assets/img/newNatalie.jpeg',
    amount: 5,
    color: 'Red',
    price: 449,
    size: 40,
    collection: 2022,
    description: 'Czerwone lakierowane szpilki z noskami w szpic',
    marka: 'Kazar',
    popular: false,
  },
  {
    id: '61372-01-P1',
    name: 'MALVA',
    img: './assets/img/malva.jpeg',
    amount: 5,
    color: 'Pink',
    price: 369,
    size: 36,
    collection: 2021,
    description: 'Różowe klapki damskie',
    marka: 'Kazar',
    popular: false,
  },
  {
    id: '61101-01-00',
    name: 'KATIA',
    img: './assets/img/katia.jpeg',
    amount: 103,
    color: 'Black',
    price: 299,
    size: 39,
    collection: 2021,
    description: 'Czarne klapki damskie',
    marka: 'Kazar',
    popular: false,
  },
  {
    id: '70317-L0-00',
    name: 'KOZDRA',
    img: './assets/img/kozdra.jpeg',
    amount: 2,
    color: 'Black',
    price: 699,
    size: 41,
    collection: 2022,
    description: 'Czarne lakierowane półbuty na grubej podeszwie',
    marka: 'CCC',
    popular: true,
  },
  {
    id: '66855-01-09',
    name: 'CORNELIE',
    img: './assets/img/cornelia.jpeg',
    amount: 1,
    color: 'Green',
    price: 599,
    size: 38,
    collection: 2022,
    description: 'Zielone sandały z kwadratowym noskiem',
    marka: 'Kazar Studio',
    popular: false,
  },
  {
    id: '70412-32-A5',
    name: 'HARLEY',
    img: './assets/img/harley.jpeg',
    amount: 25,
    color: 'Lily',
    price: 199,
    size: 37,
    collection: 2020,
    description: 'Liliowe sandały z tłoczonego nubuku na szerokim obcasie',
    marka: 'Kazar',
    popular: false,
  },
];

export const getProducts = (): Promise<ProductFromServer[]> => {
  return Promise.resolve(products);
};
